### PR TITLE
Use Auth-Enabled Figgy Viewer

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by hackmastera** [comment]
has it been deployed?

**Comment by tpendragon** [comment]
Yes, this is in staging atm.

**Comment by hackmastera** [comment]
I mean has the viewer been deployed in figgy such that if this is merged / deployed it will be there

**Comment by tpendragon** [comment]
Oh! The viewer's there but it'll look weird until https://github.com/pulibrary/figgy/pull/3215 is merged/deployed.

**Pull request merged**
