### PR TITLE
Use bulk google API and add covers to search.

### LINKED ISSUE #301: Covers in search results
Let's give it a try.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #301

### CODE REVIEW

**Comment by tpendragon** [comment]
If this gets merged and deployed, the solr config on the staging server will have to get updated.

**Comment by jpstroop** [comment]
:+1: The only thing I notice is that w/ e.g. 4131923 the image is getting upsampled:

http://localhost:3000/catalog/4131923 

https://books.google.com/books/content?id=7zZnAAAAMAAJ&printsec=frontcover&img=1&zoom=5

it doesn't seem like that `zoom` param actually does anything, so maybe we should just let the browser figure out the size?

**Comment by tpendragon** [comment]
@jpstroop I don't process any of the parameters right now, I just accept the thumbnail parameter from google books. When I ask for the URL without the zoom level for some images I don't get anything back.

**Comment by tpendragon** [comment]
Oh, I see, you're saying don't restrict the size of the thumbnail element so that it can be smaller/larger if necessary?

**Comment by jpstroop** [comment]
> Oh, I see, you're saying don't restrict the size of the thumbnail element so that it can be smaller/larger if necessary?

Yes, that.

**Comment by jpstroop** [comment]
Though: https://books.google.com/books/content?id=7zZnAAAAMAAJ&printsec=frontcover&img=1&zoom=1

**Comment by tpendragon** [comment]
Changed the CSS. I can manipulate the zoom level to 1, but I don't think google is providing any promises with that since it's not returned in the API.

**Comment by tpendragon** [comment]
Changing zoom to 1 seems to work.

**Comment by jpstroop** [comment]
Every image in the test set responds to zoom=1. I think you should try it. Some of them also include a param `edge=curl` which I think we should strip.

**Comment by tpendragon** [comment]
> Every image in the test set responds to zoom=1. I think you should try it. Some of them also include a param edge=curl which I think we should strip.

Done.

**Comment by jpstroop** [comment]
OK. I can merge assuming there's :green_heart: from Travis, but do you want to muck w/ Solr?

**Pull request merged**
