### PR TITLE
Use custom Solr docker image and remove solr_wrapper

### LINKED ISSUE #2364: Fully enable lando and remove solr wrapper
Current status: Lando is in, but solr wrapper hasn't been removed. We've haven't figured out how to get the solr plugin jars to work. There might be a way to upload them?

### PR DESCRIPTION
**Pull request by eliotjordan**
- Creates a custom Solr image that allows installation of CJKFoldingFilter and lucene-umich-solr-filters plugins  and bundles a dummy authentication document.

See:
https://github.com/pulibrary/ci-solr-docker
https://hub.docker.com/repository/docker/pulibrary/ci-solr
https://hub.docker.com/repository/docker/pulibrary/orangelight-solr

- Modernizes the CircleCI config and adds a separate rubocop job
- Removes solr_wrapper dependency
- Adds checked-in copy of solr configuration for convenience

Closes #2364

### CODE REVIEW

**Comment by tpendragon** [comment]
I am so, so excited about this. How does the docker image get built and pushed to docker hub?

**Comment by eliotjordan** [comment]
@tpendragon DockerHub used to watch your repos and rebuild automatically, but that's now a paid-only option. :( You have to do it manually, but it's easy:

```
cd solr/docker/
docker login # login to docker hub
docker build -t pulibrary/orangelight-solr:8.4 .
docker push pulibrary/orangelight-solr:8.4
```

**Comment by tpendragon** [comment]
@eliotjordan Can you add that documentation to ci-solr-docker? I wonder if someday we can make CircleCI build and push it on merge to master - not important for no,w though.

**Comment by eliotjordan** [comment]
@tpendragon Added those instructions to the ci-solr-docker README.

**Review by tpendragon — APPROVED** [review]

**Review by tpendragon — COMMENTED** [review]
I guess the only concern I have is that now CI won't be testing the latest version of what's in pul_solr, since the files are committed. Do you have any worries there?

**Comment by eliotjordan** [comment]
I don't. The schema doesn't change _that_ often, and it's easy to pull in with a rake task. We do this in other projects, and it's never been a problem.

**Pull request merged**
