### PR TITLE
Adjusts the show Document view to render title_citation_display as the primary title and only elements of title_display as the the secondary title

### LINKED ISSUE #1425: Break up the 245 field on the show page
The current show page displays the entire 245 field, e.g., 
```a| The neighborhoods of Brooklyn / c| introduction by Kenneth T. Jackson ; John B. Manbeck, consulting editor. ```
See: https://catalog.princeton.edu/catalog/4246093. 

It would be much more readable if we could display 245a and 245c on two different lines as different html elements. See: https://xd.adobe.com/view/2dcc57fd-3f03-4e5d-4a31-1493c363013c-5bfd/screen/dcad339b-b3b9-4382-8060-b364a2b7f7eb/Catalog-Item-Record-Book

Related to #1313

Child of #1314

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1425

### CODE REVIEW

**Comment by escowles** [comment]
Looks like the Github-resolve-conflicts updates I made resulted in RuboCop failures.  Also, I'm seeing a single "." as the h2 in https://catalog-staging.princeton.edu/catalog/4609321:

```
 <h1 dir="ltr"> Bible, Latin </h1>
 <h2 itemprop="name">.</h2>
```

**Comment by tampakis** [comment]
Don't merge into master until showpage redesign is approved by Lissc+

**Comment by escowles** [comment]
This looks good to me — should we merge this into `show_page_layout` @tampakis @axamei ?

**Comment by tampakis** [comment]
Address merge conflicts, attach screenshots, and discuss again with DSSG

**Pull request closed without merging**
