### PR TITLE
Update requestsjs - breakdown requestable function to smaller functions

### LINKED ISSUE #3512: Improve requests.js file
Following the work https://github.com/pulibrary/orangelight/pull/3511 improve more the requests.js file.

### PR DESCRIPTION
**Pull request by christinach**
closes #3512

### CODE REVIEW

**Comment by christinach** [comment]
examples:
https://catalog-qa.princeton.edu/requests/998574693506421?aeon=false&mfhd=22579850750006421 (there is a small bug when there are a lot of items, but it wont prevent the user to request the item or request more. I'll demo this in the checkin. The catalog production site currently has a bug that will prevent the user to request more than one items if you unselect some of the selected ones.)

https://catalog-qa.princeton.edu/requests/99126746975306421?aeon=false&mfhd=22955593460006421

https://catalog-qa.princeton.edu/requests/99110528583506421?aeon=false&mfhd=22732237860006421

https://catalog-qa.princeton.edu/requests/99115215833506421?aeon=false&mfhd=22703340470006421

https://catalog-qa.princeton.edu/requests/99115215823506421?aeon=false&mfhd=22703374900006421

https://catalog-qa.princeton.edu/requests/99122304923506421?aeon=false&mfhd=22511126440006421

https://catalog-qa.princeton.edu/requests/9928652563506421?aeon=false&mfhd=22709024380006421

https://catalog-qa.princeton.edu/requests/99126743805306421?aeon=false&mfhd=22954825980006421

https://catalog-qa.princeton.edu/requests/99118269913506421?aeon=false&mfhd=22722909750006421

https://catalog-qa.princeton.edu/requests/99126230255306421?aeon=false&mfhd=22709114850006421

https://catalog-qa.princeton.edu/requests/SCSB-12077423?aeon=false

https://catalog-qa.princeton.edu/requests/99125410673606421?aeon=false&mfhd=22905775240006421

https://catalog-qa.princeton.edu/requests/99126743805306421?aeon=false&mfhd=22954825980006421

https://catalog-qa.princeton.edu/requests/99126743805306421?aeon=false&mfhd=22954825980006421

@kevinreiss if you think of another case can you please include it in this comment?

**Comment by kevinreiss** [comment]
I noticed one issue that I would classify as bug we may want to fix before releasing this, with an in process item on a multi-item form. Selecting only hte in process row does not activate the request button: 
https://catalog-qa.princeton.edu/requests/998574693506421?aeon=false&mfhd=22579850750006421

4th item is in process.

**Comment by kevinreiss** [comment]
A couple of other items that I might ticket if others agree. The E-delivery validation is a bit wonky still. 

If you select the row, then select e-delivery the button activates before you type a title. If you submit w/o a title it errors and forces yo to write in so it is not a major blocker: https://catalog-qa.princeton.edu/requests/99122304923506421?aeon=false&mfhd=22511126440006421

For the fill in option it's the same behvior but the form doesn't highlight the missing title field you just get an error at the bottom of the page:
https://catalog-qa.princeton.edu/requests/99110528583506421?aeon=false&mfhd=22732237860006421

Again I don't view these two as blockers for this general fix.

**Comment by christinach** [comment]
> A couple of other items that I might ticket if others agree. The E-delivery validation is a bit wonky still.
> 
> If you select the row, then select e-delivery the button activates before you type a title. If you submit w/o a title it errors and forces yo to write in so it is not a major blocker: https://catalog-qa.princeton.edu/requests/99122304923506421?aeon=false&mfhd=22511126440006421
> 
> For the fill in option it's the same behvior but the form doesn't highlight the missing title field you just get an error at the bottom of the page: https://catalog-qa.princeton.edu/requests/99110528583506421?aeon=false&mfhd=22732237860006421
> 
> Again I don't view these two as blockers for this general fix.


@kevinreiss yes. We're seeing this behavior in production as well. It's a known issue.

**Comment by christinach** [comment]
> I noticed one issue that I would classify as bug we may want to fix before releasing this, with an in process item on a multi-item form. Selecting only hte in process row does not activate the request button: https://catalog-qa.princeton.edu/requests/998574693506421?aeon=false&mfhd=22579850750006421
> 
> 4th item is in process.

Good catch. I think I noticed this as well and then I forgot about it :). I'll fix this.

**Comment by kevinreiss** [comment]
Weird edge case with an item in a preservation work order: https://catalog.princeton.edu/requests/9942430233506421?aeon=false&mfhd=22600149340006421 Ask Marie if the item that is not available is in a "correct" work order for preservation.

**Comment by kevinreiss** [comment]
I retested all these scenarios. They are looking good to me. I think this ready to merge.

**Review by kevinreiss — APPROVED** [review]

**Pull request merged**
