### PR TITLE
Add fonts

### PR DESCRIPTION
**Pull request by tampakis**
Match library footer

Adjust spacing and font sizes for facets

Add main catalog to header

Make search text for search button visible to screen readers only

Move search constraints and did you mean to top of results

Consistent cross-browser select styles for search box

### CODE REVIEW

**Comment by jpstroop** [comment]
Is it just me or is this a lot to be sending over the wire? Is this typical these days, @kevinreiss ?

**Comment by kevinreiss** [comment]
@jpstroop We were having a lot of cross browser issues with web fonts so we
switched to this approach where all the font files are included.

**Comment by jpstroop** [comment]
OK. Seems like sending fonts is expensive no matter what:

http://www.webpagetest.org/result/150709_GX_18KS/1/details/

**Comment by kevinreiss** [comment]
Yes, it isn't good, especially on 3G. I think we can possibly do more with compression. On library.princeton.edu they are served from varnish when on port 80 and get an indefinite cache header which does help some.

**Comment by kevinreiss** [comment]
Or we could get serious and use something like https://typekit.com/.

**Pull request merged**
