### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by escowles**
After rebasing @tpendragon 's `rails5` branch, I see a single test failure:

```
  1) Availability multiple locations within a single holding individual locations display and do not trigger unavailable label
     Failure/Error: expect(page).to have_selector 'li', text: 'vol.2: East Asian Library - Reserve - Available (Not charged)'
       expected to find css "li" with text "vol.2: East Asian Library - Reserve - Available (Not charged)" but there were no matches. Also found "Help", "Feedback", "Your Account", "", "", "Advanced Search", "Bookmarks (0)", "Course Reserves", "Cite", "Send to", "", "", "", "", "", "", "Bookmark", "Bloom, Irene [Browse]", "Chan, Wing-tsit, 1901-1994 [Browse]", "Lufrano, Richard John, 1952- [Browse]", "Staff view", "Main Catalog", "Vol. 1-v. 2", "Vol. 1-v. 2", "Vol. 1-v. 2", "Vol. 1-2", "Vol. 1", "Data and Statistics", "Databases", "E-journals", "Research Guides", "Main Catalog", "New Catalog", "Search", "Special Collections", "Article Express", "Borrow Direct", "Circulation", "Course Reserves", "Interlibrary Loan (ILL)", "Library Access", "Study Spaces and Lockers", "Trace a Book", "Your Accounts", "Collections and Collecting", "Exhibitions", "Library Locations", "For Alumni", "For Library Staff", "Staff Directory", "Friends of the Library", "Using the Library Off-Campus", which matched the selector but not all filters.
     # ./spec/features/availability_spec.rb:51:in `block (3 levels) in <top (required)>'
```

This test also fails for me on master when I run it locally (it's skipped in Travis).

### CODE REVIEW

**Comment by kevinreiss** [comment]
I think that one is dependent on a live bibdata call and the underlying item location or status has changed.

**Comment by escowles** [comment]
@kevinreiss That makes sense.  Can we use a different item and/or stub it out or use VCR?  Either way, it doesn't seem like a blocker for upgrading to rails 5.

**Comment by kevinreiss** [comment]
The spec starting on line 35 in availability_spec.rb seems to be testing what I thought this one does - temp reserve location display. @tampakis any thoughts  on what this one was actually supposed to do? I think it possibly can just be deleted.

**Comment by tampakis** [comment]
yeah I'm thinking we can delete it. We've never been able to stub it because the data gets brought in via an AJAX call to marc liberation.

**Comment by escowles** [comment]
OK, I've pushed a commit to remove that test.  I'll add a ticket to see if we can use VCR to handle those external calls to bibdata.

**Comment by kevinreiss** [comment]
Hi, this looks good to me. I deployed it to pulsearch-dev and have it used it locally. @tampakis what do you think? We should pin this to commithttps://github.com/pulibrary/requests/releases/tag/0.01-alpha1 on the requests gem if we are thinking of putting it into production sooner rather than. A number of new features have been merged in there but those shouldn't go into production until the new recap SCSB system comes online.

**Comment by escowles** [comment]
@kevinreiss Looks like we need to update that requests tag to allow rails 5.1, instead of `< 5.1`.

**Comment by kevinreiss** [comment]
@tampakis @escowles this is running on pulsearch-dev now. It looks pretty good to me. What other steps or issues we need to consider be we merge and roll it out to production?

**Comment by kevinreiss** [comment]
@tampakis @escowles shall we merge this or do you think we should do more testing in local development environments and on pulsearch-dev?

**Comment by escowles** [comment]
@kevinreiss I think this is good to merge, but I don't know what the normal testing/release process for OL is.

**Comment by tampakis** [comment]
Merging!

**Pull request merged**
