### PR TITLE
Implementing date-based sorting for call numbers in the browse lists

### LINKED ISSUE #1341: LC Call number sorting with Date
Fix the order of this:
M3 G32 2017q vol. 5 
M3 .G32 1972q

Should be:
M3 .G32 1972q
M3 G32 2017q vol. 5 

From the search:
https://catalog.princeton.edu/browse/call_numbers?search_field=browse_cn&q=m3+g32+2017q
The desired call number is found at the bottom of the previous page.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1341

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
This should have extended test coverage and better code documentation.

**Comment by tampakis** [comment]
@jrgriffiniii would you consider adding this functionality to the lcsort gem? https://github.com/pulibrary/lcsort

**Comment by jrgriffiniii** [comment]
@tampakis  I'll proceed by working to resolve this on https://github.com/pulibrary/lcsort/issues/14

**Comment by jrgriffiniii** [comment]
Closed in response to https://github.com/pulibrary/lcsort/pull/15 and #1367

**Pull request closed without merging**
