### PR TITLE
Upgrade nodejs to 16.14

### PR DESCRIPTION
**Pull request by sandbergja**
related to #2871

### CODE REVIEW

**Comment by christinach** [comment]
@sandbergja thank you! we should first provision the orangelight boxes with ansible and the nodejs upgrade and then merge and deploy this. We usually test everything on staging first (or QA since Orangelight has QA box as well).

**Review by christinach — COMMENTED** [review]
https://github.com/pulibrary/orangelight/pull/2872#issuecomment-1050103044

**Comment by sandbergja** [comment]
Currently, qa is on node 16.14.0.  Staging and prod are on 12.22.8.  We should try upgrading the staging box next.

**Comment by sandbergja** [comment]
rebased to fix a merge conflict

**Comment by sandbergja** [comment]
The boxes are all now provisioned with nodejs 16.14.2.

**Review by christinach — APPROVED** [review]

**Pull request merged**
