### PR TITLE
Add .ruby-version for version managers such as chruby, fixes #1027

### LINKED ISSUE #1027: Add ruby version to Gemfile, .ruby-version
Questions:
* I've added a `.ruby-version` to be used by chruby. Not sure whether this would be compatible with whatever ruby version managers y'all are using. Do you prefer me to check in this file or add it to `.gitignore`?

* How do y'all feel about adding the ruby version to the Gemfile? This will make it impossible to run under a different version.

### PR DESCRIPTION
**Pull request by hackmastera**

### CODE REVIEW

**Comment by escowles** [comment]
We're using 2.3.1 for Travis (https://github.com/pulibrary/orangelight/blob/master/.travis.yml#L4) — shouldn't we be using the same here?

**Comment by hackmastera** [comment]
hm, I was basing it on https://github.com/pulibrary/orangelight/issues/914 which I think reflects the actual production boxes, except for one which is running a later version (don't remember which exactly).

If our prod boxes are 2.2.3 maybe we should change travis.

**Comment by escowles** [comment]
Yes, switching Travis to 2.2.3 seems reasonable to me, until we can upgrade the production boxes to 2.4.x.

**Comment by hackmastera** [comment]
okay, pushed that up so I guess we'll see if travis likes it!

**Pull request merged**
