### PR TITLE
Mock bibdata /bibliographic path, refs #1082

### LINKED ISSUE #1082: Stub server-side calls to external APIs with webmock
breaking this out from #656

### PR DESCRIPTION
**Pull request by hackmastera**
Fixes #1082

### CODE REVIEW

**Comment by hackmastera** [comment]
I will rebase. Should have done those in 1 pr.

**Comment by escowles** [comment]
@hackmastera I just resolved it in the web UI.

**Comment by hackmastera** [comment]
@escowles thanks. I'm gonna add one more small commit onto this real quick, to remove the umlaut exclusion.

**Comment by hackmastera** [comment]
now merging this will resolve #1082

**Pull request merged**
