### PR TITLE
Updating requests to add user information to service error emails

### PR DESCRIPTION
**Pull request by carolyncole**

### CODE REVIEW

**Review by hackartisan — COMMENTED** [review]
I would have expected just the requests SHA to change. Why are there many other updates in the Gemfile.lock?

**Review by kevinreiss — APPROVED** [review]

**Comment by carolyncole** [comment]
@hackartisan I just ran `bundle update requests`. I have noticed that sometimes other gems get updated, but I am unsure why.
I never question bundler though... See the full output below.
```
colec@ltopmaccole[~/projects/orangelight (request-problem-user-info)⚡]> bundle update requests
Fetching https://github.com/pulibrary/borrow_direct.git
Fetching https://github.com/pulibrary/requests.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies.......
Using rake 12.3.3
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using thread_safe 0.3.6
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.6.1 (was 2.5.3)
Using racc 1.5.2
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.8 (was 2.5.7)
Using websocket-extensions 0.1.5
Using mini_mime 1.1.0
Using arel 9.0.0
Using marcel 1.0.1
Using public_suffix 4.0.5
Using mime-types-data 3.2021.0704
Using multi_xml 0.6.0
Using xml-simple 1.1.8
Using amq-protocol 2.3.0
Using ast 2.4.0
Using execjs 2.8.1
Using babel-source 5.8.35
Using backport 1.1.2
Using bcrypt 3.1.16
Using jaro_winkler 1.5.4
Using unf_ext 0.0.7.7
Using powerpack 0.1.2
Using parallel 1.19.1
Using hashie 3.6.0
Using http-form_data 2.1.1
Using http_parser.rb 0.6.0
Using httpclient 2.8.3
Using slop 3.6.0
Using yell 2.2.0
Using parslet 1.8.2
Using popper_js 1.16.0
Using ffi 1.15.3
Using tilt 2.0.10
Using byebug 11.0.1
Using regexp_parser 1.6.0
Using rainbow 3.0.0
Using coffee-script-source 1.12.2
Using rb-fsevent 0.10.3
Using chronic 0.10.2
Using cobravsmongoose 0.0.2
Using coderay 1.1.2
Using json 2.5.1
Using docile 1.3.2
Using simplecov-html 0.10.2
Using tins 1.21.1
Using safe_yaml 1.0.5
Using msgpack 1.3.1
Using orm_adapter 0.5.0
Using diff-lcs 1.3
Using multipart-post 2.1.1
Using hashdiff 1.0.0
Using high_voltage 3.0.0
Using honeybadger 4.5.1
Using jquery-datatables 1.10.20
Using lcsort 0.9.1
Using logstash-event 1.2.02
Using maruku 0.7.3
Using modernizr-rails 2.7.1
Using net-ldap 0.17.0
Using pg 1.2.3
Using rdoc 6.3.0
Using dot-properties 0.1.3
Using retriable 3.1.2
Using rspec-support 3.8.2
Using rubyzip 1.3.0
Using semantic_range 3.0.0
Using sigdump 0.2.4
Using yard 0.9.25
Using spring 2.1.0
Using string_rtl 0.1.0
Using stringex 2.5.2 from https://github.com/pulibrary/stringex.git (at vpton.2.5.2.2@357f705)
Using childprocess 2.0.0
Using timecop 0.9.4
Using yajl-ruby 1.4.1
Using i18n 1.8.10
Using tzinfo 1.2.9
Using nokogiri 1.12.1 (x86_64-darwin) (was 1.11.7)
Using rack-test 1.1.0
Using websocket-driver 0.7.5
Using mail 2.7.1
Using addressable 2.7.0
Using mime-types 3.3.1
Using autoprefixer-rails 10.3.1.0 (was 10.2.5.1)
Using babel-transpiler 0.7.0
Using parser 2.7.1.1
Using sprockets 3.7.2
Using bunny 2.14.2
Using warden 1.2.9
Using request_store 1.4.1
Using rack-proxy 0.6.5
Using sitemap_generator 6.0.2
Using voight_kampff 1.1.3
Using ruby-progressbar 1.10.1
Using net-ssh 5.2.0
Using borrow_direct 1.2.0 from https://github.com/pulibrary/borrow_direct.git (at generate_query_encoding_fix@bef881c)
Using kaminari-core 1.2.1
Using rb-inotify 0.10.0
Using bundler 2.2.17
Using omniauth 1.9.1
Using coffee-script 2.4.1
Using simplecov 0.16.1
Using term-ansicolor 1.7.1
Using crack 0.4.3
Using ddtrace 0.27.0
Using faraday 0.17.4
Using whenever 0.11.0
Using rspec-core 3.8.2
Using rspec-expectations 3.8.4
Using rspec-mocks 3.8.1
Using serverengine 2.0.7
Using activesupport 5.2.6
Using loofah 2.11.0 (was 2.10.0)
Using httparty 0.18.1
Using xpath 3.2.0
Using launchy 2.4.3
Using reverse_markdown 1.4.0
Using sdoc 2.1.0
Using selenium-webdriver 3.142.4
Using sprockets-es6 0.9.2
Using net-scp 2.0.0
Using method_source 0.9.2
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.3.0
Using globalid 0.5.2 (was 0.4.2)
Using activemodel 5.2.6
Using ezwadl 0.1.0
Using deprecation 1.0.0
Using jbuilder 2.9.1
Using sshkit 1.20.0
Using capybara 3.29.0
Using sass-listen 4.0.0
Using factory_bot 5.0.2
Using global 1.1.0
Using omniauth-cas 1.1.1
Using rsolr 2.2.1
Using solr_wrapper 2.2.0
Using webdrivers 4.1.2
Using webmock 3.7.3
Using thor 0.20.3
Using library_stdnums 1.6.0
Using scrub_rb 1.0.1
Using uglifier 4.1.20
Using unf 0.1.4
Using sassc 2.4.0
Using unicode-display_width 1.4.1
Using actionview 5.2.6
Using activejob 5.2.6
Using activerecord 5.2.6
Using alma 0.3.2
Using rubocop 0.63.1
Using marc 1.0.4
Using domain_name 0.5.20190701
Using capistrano 3.4.1
Using sass 3.7.4
Using coveralls 0.8.23
Using email_validator 2.2.3
Using pry 0.12.2
Using sneakers 2.11.0
Using actionpack 5.2.6
Using rubocop-rspec 1.31.0
Using kaminari-actionview 1.2.1
Using kaminari-activerecord 1.2.1
Using marc-fastxmlwriter 1.0.0
Using http-cookie 1.0.3
Using capistrano-bundler 1.6.0
Using friendly_id 5.1.0
Using openurl 1.0.0
Using pry-byebug 3.7.0
Using solargraph 0.38.0
Using actioncable 5.2.6
Using actionmailer 5.2.6
Using activestorage 5.2.6
Using bixby 2.0.0
Using kaminari 1.2.1
Using railties 5.2.6
Using sprockets-rails 3.2.2
Using http 3.3.0
Using capistrano-rails 1.4.0
Using faraday-cookie_jar 0.0.6
Using rails-controller-testing 1.0.4
Using jquery-rails 4.4.0
Using rails 5.2.6
Using traject 3.2.0
Using mail_form 1.8.0
Using rspec-rails 3.8.2
Using webpacker 5.2.1
Using simple_form 5.1.0
Using lograge 0.11.2
Using blacklight 7.0.1
Using yaml_db 0.7.0
Using sassc-rails 2.1.2
Using font-awesome-rails 4.7.0.5
Using blacklight_advanced_search 7.0.0.alpha from https://github.com/projectblacklight/blacklight_advanced_search (at master@ae7e3b7)
Using blacklight_range_limit 7.1.0
Using blacklight_unapi 0.1.0 from https://github.com/pulibrary/blacklight_unapi.git (at master@79ac4bf)
Using bootstrap 4.6.0
Using sass-rails 5.0.7
Using responders 3.0.1
Using introjs-rails 2.1.0 from https://github.com/videmor/intro.js-rails.git (at update.introjs@6638f10)
Using factory_bot_rails 5.0.2
Using blacklight-marc 7.0.0.rc1 from https://github.com/projectblacklight/blacklight-marc.git (at c0ff1d9@c0ff1d9)
Using devise 4.8.0
Using coffee-rails 4.2.2
Using devise-guests 0.7.0
Using requests 0.0.2 from https://github.com/pulibrary/requests.git (at main@1147897)
Using chosen-rails 1.8.7
Bundle updated!
```

**Comment by hackartisan** [comment]
I see. I usually prefer to run, e.g. `bundle update --conservative requests`. I won't block this PR, though. I don't think we have any official position on this departmentally.

**Comment by carolyncole** [comment]
@hackartisan I did not know there was a `--conservative` switch. Good to know!

**Pull request merged**
