### PR TITLE
Alternative proposal for availability indication

### PR DESCRIPTION
**Pull request by jpstroop**
Perhaps another way to skin #107?

It's not fully baked--some records still show the more info glyphicon for some reason, and I think we'd want to work on getting the labels to be a consistent width.

Just an idea...

### CODE REVIEW

**Comment by jpstroop** [comment]
screenshot from 2015-10-16 10 57 34

**Comment by jpstroop** [comment]
ping @terrellt @kevinreiss @tampakis

**Comment by kevinreiss** [comment]
I like the presentation of this with the colored background and text instead of an icon, but I still think staff are probably going to want to see the status, but we can see if it comes up.

**Comment by jpstroop** [comment]
The text for the label is the status. I just added a hook to change "Not Charged" to "Available" because English.

**Comment by jpstroop** [comment]
https://github.com/pulibrary/orangelight/blob/availability_labels/app/assets/javascripts/availability.js.coffee#L30-L36

screenshot from 2015-10-16 11 16 46

**Comment by terrellt** [comment]
:+1: Works for me. The reason the info label is showing up sometimes is because sometimes ruby handles the display. https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L56

**Comment by terrellt** [comment]
We were talking about this in slack, but to document: I think it'd be good to have bibdata return what a status means (available or not), so that we don't inevitably duplicate that logic.

**Comment by jpstroop** [comment]
I'll change that on this PR

**Comment by kevinreiss** [comment]
+1 to that @terrellt.

**Comment by jpstroop** [comment]
I just squashed these ... I (humbly) think this is avenue we should pursue.

**Comment by tampakis** [comment]
I agree that this is heading in the right direction. The part that will be a challenge is (as @jpstroop said), getting the labels to be a consistent width and determining the correct amount of left padding to fit the different status codes to be pulled in next to the holding info (so the alignment is consistent).

**Comment by jpstroop** [comment]
> getting the labels to be a consistent width

I'm sure we can solve that and think we should forge ahead

**Comment by terrellt** [comment]
:+1: We can merge this and open a ticket to refactor with an updated bibdata API (pointing to bibdata ticket). Agreed?

**Comment by terrellt** [comment]
The only thing that may become trouble is the increased width in regard to mobile displays.

**Pull request merged**
