### PR TITLE
2486 exclude electronic portfolio s theses from online markup

### LINKED ISSUE #2486: Exclude theses from the electronic portfolio markup
(For alma) We use the OnlineHoldingsMarkupBuilder to create and add the online links in the online section using the `electronic_portfolio_s` field. 
The same field is added in https://github.com/pulibrary/orangetheses/pull/59/files#diff-9415cee3ad92b38bfe0abb0a30dfbd15b181b9d03915e22ec0e1b0ea09fb2b44R416 to update holding locations for Theses using the orangetheses repository. 
The online section for theses is populated using the `electronic_access_1display` field and it only includes the ark identifier `"{\"http://arks.princeton.edu/ark:/88435/dsp01r207ts08x\":[\"DataSpace\",\"Full text\"]}"`
When the electronic_portfolio_s field has a thesis key we should exclude the creation of online links in the Online section.

### PR DESCRIPTION
**Pull request by christinach**
closes #2486

### CODE REVIEW

**Comment by christinach** [comment]
This is ready for review. It would be good to deploy first on alma_qa. I tested on staging.

**Comment by christinach** [comment]
I posted/indexed in sole staging this electronic thesis record with filed electronic_portfolio_s for testing https://catalog-alma-qa.princeton.edu/catalog/dsp01w6634604k/.
https://catalog-alma-qa.princeton.edu/catalog/dsp01w6634604k/raw
``[
  {
    "id": "dsp01w6634604k",
    "title_t": "Unfinished Business: An Examination of Unrevived, Unproduced, and Incomplete Musical Theatre",
    "title_citation_display": "Unfinished Business: An Examination of Unrevived, Unproduced, and Incomplete Musical Theatre",
    "title_display": "Unfinished Business: An Examination of Unrevived, Unproduced, and Incomplete Musical Theatre",
    "title_sort": "unfinishedbusinessanexaminationofunrevivedunproducedandincompletemusicaltheatre",
    "author_sort": "Plunkett, William Anderson",
    "electronic_access_1display": "{\"http://arks.princeton.edu/ark:/88435/dsp01w6634604k\":[\"DataSpace\",\"Full text\"]}",
    "restrictions_note_display": null,
    "call_number_display": "AC102",
    "call_number_browse_s": "AC102",
    "language_facet": [
      "English"
    ],
    "author_display": [
      "Plunkett, William Anderson"
    ],
    "author_s": [
      "Plunkett, William Anderson",
      "Wolf, Stacy",
      "Wolff, Tamsen",
      "Princeton University. Program in Theater"
    ],
    "advisor_display": [
      "Wolf, Stacy"
    ],
    "contributor_display": [
      "Wolff, Tamsen"
    ],
    "certificate_display": [
      "Princeton University. Program in Theater"
    ],
    "description_display": [
      "82 pages"
    ],
    "access_facet": "Online",
    "electronic_portfolio_s": "{\"thesis\":{\"call_number\":\"AC102\",\"call_number_browse\":\"AC102\",\"dspace\":true}}",
    "class_year_s": [
      "2016"
    ],
    "pub_date_start_sort": [
      "2016"
    ],
    "pub_date_end_sort": [
      "2016"
    ],
    "format": "Senior thesis"
  }
]``

**Comment by christinach** [comment]
it is also included in the online facet https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Unfinished+Business%3A+An+Examination+of+Unrevived%2C+Unproduced%2C+and+Incomplete+Musical+Theatre

**Comment by christinach** [comment]
After we merge this PR I can re-index theses in solr-staging, for catalog-alma-qa.

**Review by bess — APPROVED** [review]

**Comment by christinach** [comment]
@bess can you re-review? I rebased and force pushed. I changed the base branch to be `alma` and not `main`. We decided that 10 mins ago in slack.

**Review by hackartisan — APPROVED** [review]

**Review by bess — APPROVED** [review]

**Pull request merged**
