### PR TITLE
Updated home page language

### PR DESCRIPTION
**Pull request by escowles**

### CODE REVIEW

**Review by hackartisan — COMMENTED** [review]
Suggestion: "Requesting items from ReCAP will remain unavailable until August 8" might sound good

**Comment by escowles** [comment]
@hackartisan 👍🏻 That's a good suggestion, I'll make the change!

**Comment by escowles** [comment]
Current proposed language:
>Our system upgrade is nearly complete and most materials can now be requested again. Requesting items from ReCAP will remain unavailable until August 8. Please see [our announcement](https://library.princeton.edu/news/general/2021-08-02/pul-launch-new-library-system-summer-2021-hathitrust-etas-update) for more information.

**Review by christinach — APPROVED** [review]

**Review by hackartisan — APPROVED** [review]
Thanks!

**Pull request merged**
