### PR TITLE
Refactor item record display

### LINKED ISSUE #292: Refactor record view
* Move the thumbnail to the left side of the screen
 * Move the metadata slightly right to make room for the above
 * Move the availability window up to the top

I.E.:
 
md_layout_refactor

### PR DESCRIPTION
**Pull request by terrellt**
Closes #292

### CODE REVIEW

**Comment by terrellt** [comment]
Looks like this: 
screen shot 2015-10-15 at 1 15 45 pm

**Comment by jpstroop** [comment]
Let's go with it if travis is :green_heart: . Still wish the graphic was centered, or at least not flush w. the start of the title

**Comment by terrellt** [comment]
@jpstroop Just updated it to make it not flush. It wasn't for the icons, but the covers weren't centering.

**Comment by terrellt** [comment]
screen shot 2015-10-15 at 2 29 07 pm

**Pull request merged**
