### PR TITLE
Prevents suspected bots from viewing availability information for catalog records

### LINKED ISSUE #1001: Don't display realtime availability info for robots
There should be a useragent-sniffing gem to make this easier.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1001

### CODE REVIEW

**Comment by escowles** [comment]
The [Voight-Kampff README](https://github.com/biola/Voight-Kampff#configuration) mentions a Rake task that will download an updated list of bob user agent strings and save it in `config`.  Do we want to do that and checkin that file? Or run the rake task at deploy time?

**Comment by tampakis** [comment]
This looks great @jrgriffiniii! My only concern is with the scope of which content to exclude from bots. The show availability sidebar partial includes the item location information, which might be useful to keep in for bots. Also it would be great to hide the availability sections for the index and browse views. I'll come up with the places in the code where I think make the most since to exclude content.

**Comment by tampakis** [comment]
For bots, don't display:
 - Results page availability - this method in the application is nasty, but I think there are only two spots that need to be updated:
   - [set check_availability to false](https://github.com/pulibrary/orangelight/blob/master/app/helpers/application_helper.rb#L329)
   - [set check_availability to false again when link is missing](https://github.com/pulibrary/orangelight/blob/master/app/helpers/application_helper.rb#L334)
 - [Call number browse availability](https://github.com/pulibrary/orangelight/blob/master/app/views/orangelight/browsables/index.html.erb#L84-L92)

Actually, I think it's fine excluding the entire show_availability sidebar.

**Comment by tampakis** [comment]
@eliotjordan brought up a good point that it would be wise to also block bots from certain routes in OL that make connections to bibdata, at the controller level. This would include the staff view and the export formats.

**Comment by escowles** [comment]
I think blocking bots is a good idea — but do we want to do that in the load-balancer instead of in the app?

**Comment by tampakis** [comment]
When a bot requests a .endnote page would the load balancer know when orangelight makes the call to bibdata?

**Comment by escowles** [comment]
@tampakis No, I mean the load balancer would block the request if a bot requested a .endnote page, so it would never get to OL.

**Pull request merged**
