### PR TITLE
add byebug

### PR DESCRIPTION
**Pull request by eliotjordan**
Add byebug for development.

### CODE REVIEW

**Comment by tpendragon** [comment]
I wasn't there for the hydra connect talk - any reason for byebug over pry-byebug?

**Comment by eliotjordan** [comment]
@tpendragon Do you have a preference? Nikitas and I don't.

**Comment by tpendragon** [comment]
I like the formatting in pry-byebug.

**Comment by eliotjordan** [comment]
pry-byebug looks nice. I swapped it out.

**Pull request merged**
