### PR TITLE
Add Lando for test/dev solr.

### LINKED ISSUE #1986: Replace solr_wrapper with Lando
see https://github.com/pulibrary/pulfalight/pull/209/files

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #1986

### CODE REVIEW

**Comment by tpendragon** [comment]
> Can you update all the pulfalight text to orangelight?

Oop, thanks. Should be fixed now.

**Comment by christinach** [comment]
Thanks @tpendragon . Should we include the index as a step after 'lando' is up, Rake::Task['pulsearch:solr:index'].invoke, or should we add it as a different step in the README to run the rake task 'rake pulsearch:solr:index?

**Comment by christinach** [comment]
@tpendragon I approved the PR and thanks for the work. I have one question regarding the indexing step. I posted it above.

**Comment by christinach** [comment]
@tpendragon I thought about it again. It's ok to merge it and we should update the README (a different issue).

**Pull request merged**
