### PR TITLE
Add homepage card for numismatics search

### LINKED ISSUE #2049: Link to numismatics search page
Options:

1. Link from home page.
1. Link from advanced search.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #2049 

Screenshot 2020-06-01 15 26 47

Screenshot 2020-06-01 15 24 27

### CODE REVIEW

**Comment by christinach** [comment]
@eliotjordan the error is caused from  `bundle exec rake assets:precompile`. It is not from this PR.

**Comment by christinach** [comment]
@eliotjordan can you rebase and push again?

**Comment by eliotjordan** [comment]
@christinach There are no coins in staging, I presume.

**Comment by christinach** [comment]
@eliotjordan yes there are no coins.

**Pull request merged**
