### PR TITLE
Add alma-qa env

### LINKED ISSUE #1981: Add deploy for qa-alma server

### PR DESCRIPTION
**Pull request by christinach**
closes #1981

### CODE REVIEW

**Comment by christinach** [comment]
This will be ready for review next week, after we complete with @kayiwa the alma-qa OL box.

**Comment by christinach** [comment]
Please see https://catalog-alma-qa.princeton.edu/. For now it is pointing to the the catalog-staging on lib-solr8-staging  collection.

**Comment by hackmastera** [comment]
:thumbsup: approve

**Comment by christinach** [comment]
Thanks for reviewing @hackmastera

**Pull request merged**
