### PR TITLE
Add the library label in front of the location

### LINKED ISSUE #2558: Call number browse in catalog-alma does not always display the location
example: https://catalog-alma-qa.princeton.edu/browse/call_numbers?start=251

example: https://catalog-alma.princeton.edu/browse/call_numbers?q=%28Ex%29+1497.4055.12q%2C+vol.+02+%5B03+pages+after+p.+128%5D 
vs
https://catalog.princeton.edu/browse/call_numbers?q=%28Ex%29+1497.4055.12q%2C+vol.+02+%5B03+pages+after+p.+128%5D

### PR DESCRIPTION
**Pull request by christinach**
Update alma current_fixtures with new alma records
Update call_numbers.sorted based on the current_fixtures
Update availability and searching spec

closes #2558

### CODE REVIEW

**Review by hackartisan — APPROVED** [review]
Looks good! Happy to merge once we try it on the qa site.

**Comment by christinach** [comment]
I just started the rake task for the call numbers in catalog-qa1

**Comment by christinach** [comment]
before the pr:
Screen Shot 2021-07-30 at 11 19 40 AM
Screen Shot 2021-07-30 at 11 19 05 AM

**Comment by christinach** [comment]
with the fix:
Screen Shot 2021-07-30 at 12 05 56 PM
Screen Shot 2021-07-30 at 12 06 43 PM

**Pull request merged**
