### PR TITLE
update footer to match library main webpage

### LINKED ISSUE #1539: Update footer to match main Library website

### PR DESCRIPTION
**Pull request by tampakis**
Splitting out show_page_layout branch into more organized branches.
Closes #1539

### CODE REVIEW

**Comment by escowles** [comment]
This looks good except the Twitter icon isn't showing up in the footer for some reason.

**Comment by tampakis** [comment]
@escowles can you send a screenshot? I see it to the write of the facebook icon locally

**Comment by escowles** [comment]
Sorry @tampakis — looks like I'm blocking it in my main browser (I dimly remember blocking some twitter icons in news sites last fall).  I just checked another browser and it's there.

**Comment by tampakis** [comment]
Makes sense to block out the distraction ;)

**Pull request merged**
