### PR TITLE
Use Data Tables for Course Reserves page.

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by tpendragon** [comment]
Looks like this:

screen shot 2016-08-02 at 3 13 42 pm

**Comment by jpstroop** [comment]
It's looking really good. Two minor things:

First, could you make the text in the well read:

> # Course Reserves
> Search for your Course, Instructor, or Department below. Please note that every reserve location has its own loan and shelving policies. Consult library staff in the Firestone Reserve Room and at branch library circulation desks for assistance.

Second; maybe this only bugs me, but could you make all of the text along the left align?

image10

I think either that or scoot the search box label "Search by Course..." a little to the right so that it lines up with the "Course" column header.

**Comment by tpendragon** [comment]
screen shot 2016-08-03 at 9 00 09 am

**Comment by kevinreiss** [comment]
This looks ready to go to me. Thanks @tpendragon. Since everyone is on the road I'm going to merge it.

**Comment by jpstroop** [comment]
Looks great!
-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Pull request merged**
