### PR TITLE
Add jsonld as option for record export

### PR DESCRIPTION
**Pull request by maxkadel**
This code is heavily based on the jsonld code in bibdata - see https://github.com/pulibrary/bibdata/blob/e92ba310e4cc859a8b40494eee018f5e06156eb2/app/models/jsonld_record.rb.

Connected to #3072

### CODE REVIEW

**Comment by maxkadel** [comment]
There are three values that I'm not sure about
- local_identifier (currently not implemented)
  - From my reading of the code, bibdata is only displaying cicognara numbers 
  - I can't find an example of a record that uses these, and cicognara numbers don't seem like local_identifiers
  - local_identifier isn't included in https://bibdata.princeton.edu/context.json 
- identifier
  - It looks like the bibdata implementation is only displaying `iiif_manifest_paths`, so that's how I've implemented it here, but I'm not positive that is what's wanted 
- electronic_locations
  - Currently pulling from `electronic_access_1display` and displaying all of them - it does not appear that that's what's happening in bibdata - see, for example, `9946093213506421` https://bibdata.princeton.edu/bibliographic/9946093213506421/jsonld vs the "with a digitized manuscript" example in the tests on this branch.

**Comment by tpendragon** [comment]
@maxkadel 

1. We definitely use local identifier. You can see it imported here: https://figgy.princeton.edu/catalog/c2e1f051-73c6-43ba-a8cb-651a89fdd8f1, and these identifiers are used for synchronizing with Getty for https://cicognara.org

2. `identifier` should be ARKs that are in the 856, I believe? I'm not sure where that'd be in the solr record, exactly. The idea is that if there's already an ARK in there, it should import it. I think it'll only be a IIIF ARK if it was put in there from someone importing it from Figgy. I'm working from memory, but I think there used to be some logic in there to try to pick the right 856 if there were multiple, but I could be wrong.

3. I suspect this is just a side effect of the Alma -> Solr direct pipeline in Bibdata being pretty rough, since it didn't have all the data that the bulk export has. I think it's fine as you have it.

**Comment by maxkadel** [comment]
@tpendragon - am I understanding correctly that right now local_identifier should only include the Cicognara number?

**Review by tpendragon — APPROVED** [review]
I tested this in a local Figgy branch and it seems to work great.

**Review by kevinreiss — APPROVED** [review]

**Pull request merged**
