### PR TITLE
Update the banner with a new message and the homepage with an announcement 

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by christinach** [comment]
with the icon-bell:
1.Screen Shot 2020-04-07 at 7 56 14 AM
2.Screen Shot 2020-04-07 at 7 55 45 AM
3.Screen Shot 2020-04-07 at 7 54 48 AM

**Comment by christinach** [comment]
with the icon-announce:
1.Screen Shot 2020-04-07 at 7 58 28 AM

2.Screen Shot 2020-04-07 at 7 58 50 AM
3.Screen Shot 2020-04-07 at 8 00 18 AM

**Comment by escowles** [comment]
Those all look good to me — I like option 3 the best, since it's going in the direction of having the megaphone icon take a similar role to the Hathi icon above, making the multiple boxes look like desktop notifications a little bit.

**Comment by christinach** [comment]
@escowles I deployed megaphone- option 3 on staging

**Pull request merged**
