### PR TITLE
WIP: Adding announcement for downtime related to Voyager upgrade

### PR DESCRIPTION
**Pull request by escowles**

### CODE REVIEW

**Comment by escowles** [comment]
screen shot 2018-08-03 at 9 59 45 am

**Comment by jpstroop** [comment]
What about:

> The Library's Catalog is undergoing a scheduled upgrade this week. During this time, item availability, requesting (including ReCAP or Borrow Direct), or "Your Account" functionality will be not available. Catalog searching will function normally, and records will display their call numbers and shelf locations from Sunday, 8/5/18.

**Comment by tampakis** [comment]
Rather than "not available" how about "unavailable"

**Comment by jpstroop** [comment]
Oops, I mean to have "not be", not "be not", (:yoda:) but unavailable is better than both.

**Comment by escowles** [comment]
i'm trying to keep the text from spilling onto a third line, how does this sound:
> The Library Catalog is being upgraded this week to improve administrative functionality. Item availability, requesting (including ReCAP or Borrow Direct), and "Your Account" functionality will be unavailable. Searching will function normally, and records will display call numbers and shelf locations from Sunday, 8/5/18.

**Comment by tampakis** [comment]
Upgrade is complete!

**Pull request closed without merging**
