### PR TITLE
Refactor pagination tools in Browse Pages

### LINKED ISSUE #1809: Fix pagination tools on Browse pages
Screen Shot 2019-08-28 at 7 20 37 AM
Screen Shot 2019-08-28 at 7 20 58 AM

### PR DESCRIPTION
**Pull request by christinach**
closes #1809

### CODE REVIEW

**Comment by christinach** [comment]
with this update in different screens  **The top pagination:**
Screen Shot 2019-09-04 at 8 59 27 AM

Screen Shot 2019-09-04 at 8 59 17 AM

Screen Shot 2019-09-04 at 8 59 07 AM

**The bottom pagination:**
Screen Shot 2019-09-04 at 9 00 23 AM

Screen Shot 2019-09-04 at 9 00 57 AM

**Comment by tampakis** [comment]
Looks much better. Can the bottom pagination tools be moved to the center like they currently are on production?

**Comment by christinach** [comment]
I will move them @tampakis . Thanks!

**Comment by christinach** [comment]
position the bottom pagination to the **center** of the page:
Screen Shot 2019-09-04 at 10 25 53 AM
Screen Shot 2019-09-04 at 10 25 45 AM

**Comment by tampakis** [comment]
Can the Previous and Next links look like the buttons that appear on the search results/show page?

**Comment by christinach** [comment]
yes they can; this was the initial thought :)

**Comment by tampakis** [comment]
On smaller screens can the pagination tools still appear as far to the right as possible?
Screen Shot 2019-09-04 at 10 44 13 AM

**Comment by tampakis** [comment]
The pagination tools need to go on a second line for the name-title browse, can we have the controls split like they are on production in this case?
Screen Shot 2019-09-04 at 10 45 51 AM

**Comment by christinach** [comment]
can you provide specific screen size?

**Comment by christinach** [comment]
production **xs** screen
Screen Shot 2019-09-04 at 11 02 34 AM

Screen Shot 2019-09-04 at 11 13 23 AM

-------------
 production **sm** screen
Screen Shot 2019-09-04 at 11 14 25 AM


Screen Shot 2019-09-04 at 11 12 13 AM

I think the pagination in xs sm screens should be in a different line and left aligned. thoughts?

**Comment by christinach** [comment]
I updated the author-title sm screenshot in the previous comment. Accidentally I had added an `xs` one.

**Comment by christinach** [comment]
After discussing with @tampakis we decide to move forward by adding the pagination tools in a second line for `xs` `sm` screens and left align the pagination and right align the per page tool. 
we will make sure that there is enough padding between the tools in the `xs` screen. It looks better and works correctly.

**Comment by christinach** [comment]
@tampakis I have pushed an update

**Comment by tampakis** [comment]
Looks great. Just one change - on the first page of browsing the "previous" should be greyed out. On the last page the "next" should be greyed out to visually indicate that they aren't clickable

**Comment by christinach** [comment]
browse-pagination-tools

**Pull request merged**
