### PR TITLE
Updating requests to fix the library name on the request form

### PR DESCRIPTION
**Pull request by carolyncole**

### CODE REVIEW

**Comment by carolyncole** [comment]
@kevinreiss the label is fixed here: https://catalog-qa.princeton.edu/requests/99121746953506421?mfhd=22692551910006421&source=pulsearch

**Comment by christinach** [comment]
@carolyncole the branch has some conflicts.

**Comment by christinach** [comment]
@kevinreiss @carolyncole is this ok to merge?

**Comment by christinach** [comment]
hm this pr doesn't include a requests version. maybe it was already added in another pr?

**Comment by christinach** [comment]
and this is in main now https://github.com/pulibrary/orangelight/blob/1d3839cd35765b481b26aae4da0b119ce0a240d7/config/requests.yml#L33

I will close it.

**Pull request closed without merging**
