### PR TITLE
Change advanced search facet selection to bootstrap-select for accessibility

### PR DESCRIPTION
**Pull request by carolyncole**
refs #2827 

This is the first page in the ticket.  I took this approach from the Temple advanced search page: https://librarysearch.temple.edu/catalog/advanced

### CODE REVIEW

**Comment by christinach** [comment]
@carolyncole I tested it on staging. The tab key announces as expected. Where I'm confused is when the screen reader goes over the 'Limit results by' for every combo box it says 'list box' then it reads the content and in the end it announces 'Type or select access types, list box pop up, Menu pop-up combobox'. I think this message should come before reading the content? Similar behaviour with the tab key.

**Comment by carolyncole** [comment]
@christinach I updated the PR to not read the select before it is opened.  I believe that makes the most sense.  I also added a feature test for advanced search.

**Review by christinach — COMMENTED** [review]
@carolyncole the script might have overwritten some css? the search bar with the keyword are dispositioned. Can you check?  I deployed on staging.

**Comment by carolyncole** [comment]
@christinach good catch.  I removed the bootstrap styling...

**Comment by christinach** [comment]
The only difference that I see is that the width of the specific Holding Library field expands based on the content. 
Screen Shot 2022-01-18 at 10 23 17 AM

**Comment by christinach** [comment]
Other than that the PR advances the accessibility and addresses the specific issue.

**Comment by christinach** [comment]
approved by DSSG

**Review by christinach — APPROVED** [review]

**Comment by carolyncole** [comment]
@christinach my only comment is that you can use below to not change all the spacing
```
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
```

**Pull request merged**
