### PR TITLE
Embeds multiple figgy links in show page

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by christinach** [comment]
closes #960

**Comment by christinach** [comment]
closes #960

**Comment by escowles** [comment]
@christinach When I look at 4609321 using this branch, I see only one of the two objects associated with that item: https://catalog-staging.princeton.edu/catalog/4609321  — are there indexing changes needed for this to work?

**Comment by tampakis** [comment]
@escowles, that record is a special case, where I think even though there are 2 arks, they resolve to the same object in figgy.

This one's a better example: https://catalog-staging.princeton.edu/catalog/3943643

**Pull request merged**
