### PR TITLE
Add embedding of Plum Viewer when possible.

### LINKED ISSUE #426: Embed Universal Viewer for Plum Content
After the page has loaded with the bibliographic data:
1. Content Negotiate for JSON(LD) on the ARK.
2. Javascript follows the redirect (wonder if conneg will work, not sure if the headers will stick with the redirect. I expect not...we'll need to experiment)
3. If the response is an IIIF Manifest or Collection, load the viewer and display.

@escowles or @tpendragon can help as necessary--this is roughly what we discussed, yeah?

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #426

### CODE REVIEW

**Comment by jpstroop** [comment]
Is this branch still deployed? If not, could you deploy it and paste some sample links here?

Thinking I might write to LISSC for feedback.

**Comment by tpendragon** [comment]
@jpstroop Yup.

https://pulsearch-dev.princeton.edu/catalog/7849451
https://pulsearch-dev.princeton.edu/catalog/4609321
https://pulsearch-dev.princeton.edu/catalog/7849679

Plus basically anything from here: https://plum.princeton.edu/catalog?f%5Bworkflow_state_name_ssim%5D%5B%5D=complete&locale=en&q=

**Comment by tpendragon** [comment]
@jpstroop Yup.

https://pulsearch-dev.princeton.edu/catalog/7849451
https://pulsearch-dev.princeton.edu/catalog/4609321
https://pulsearch-dev.princeton.edu/catalog/7849679

Plus basically anything from here: https://plum.princeton.edu/catalog?f%5Bworkflow_state_name_ssim%5D%5B%5D=complete&locale=en&q=

**Comment by jpstroop** [comment]
Should we do #861 as part of this?

**Comment by escowles** [comment]
Do we want to try this out in staging before merging?

**Comment by tpendragon** [comment]
It's been in staging for a while - there are some links to look at a while up. Basically just waiting to see if @joycebcat's issue is fixed, and the go ahead from @jpstroop and company.

**Comment by escowles** [comment]
@joycebcat Can you confirm that your issue is now fixed and the viewer works for you?

Here are a few sample records:

https://pulsearch-dev.princeton.edu/catalog/7849451
https://pulsearch-dev.princeton.edu/catalog/4609321
https://pulsearch-dev.princeton.edu/catalog/7849679

**Comment by joycebcat** [comment]
Confirmed!  The issue is fixed and the viewer works on my mac/Safari.

**Comment by escowles** [comment]
Thanks @joycebcat — now we're just waiting on the OK from @jpstroop before we can ship this!

**Comment by jpstroop** [comment]
:shipit:

**Pull request merged**
